import httpx
from fastapi import HTTPException
from app.core.config import settings

class NetbirdClient:
    def __init__(self):
        self.base_url = settings.NETBIRD_API_URL.rstrip('/')
        self.headers = {
            "Accept": "application/json",
            "Content-Type": "application/json",
            "Authorization": f"Token {settings.NETBIRD_API_TOKEN}"
        }

    async def get_user_by_email(self, email: str) -> str | None:
        """Finds a Netbird user ID by email."""
        async with httpx.AsyncClient() as client:
            resp = await client.get(f"{self.base_url}/users", headers=self.headers)
            if resp.status_code != 200:
                print(f"Netbird API Error (get_users): {resp.text}")
                return None
            users = resp.json()
            for u in users:
                if u.get('email') == email:
                    return u.get('id')
            return None

    async def create_group(self, name: str) -> str | None:
        """Creates a group in Netbird and returns its ID."""
        async with httpx.AsyncClient() as client:
            resp = await client.post(
                f"{self.base_url}/groups", 
                headers=self.headers,
                json={"name": name}
            )
            if resp.status_code != 200:
                print(f"Netbird API Error (create_group): {resp.text}")
                return None
            return resp.json().get('id')

    async def create_setup_key(self, name: str, auto_groups: list[str]) -> str | None:
        """Creates a non-ephemeral, one-off setup key bounded to specific groups."""
        async with httpx.AsyncClient() as client:
            payload = {
                "name": name,
                "type": "one-off",
                "ephemeral": False,
                "auto_groups": auto_groups,
                "usage_limit": 1
            }
            resp = await client.post(
                f"{self.base_url}/setup-keys", 
                headers=self.headers,
                json=payload
            )
            if resp.status_code != 200:
                print(f"Netbird API Error (create_setup_key): {resp.text}")
                return None
            return resp.json().get('key')

    async def create_policy(self, name: str, source_groups: list[str], dest_groups: list[str]) -> str | None:
        """Creates an ACL policy allowing traffic from source groups to dest groups."""
        async with httpx.AsyncClient() as client:
            payload = {
                "name": name,
                "description": "Auto-generated by VDI Manager",
                "enabled": True,
                "rules": [
                    {
                        "name": f"{name} Rule",
                        "description": "Auto-generated rule",
                        "enabled": True,
                        "action": "accept",
                        "protocol": "all",
                        "sources": source_groups,
                        "destinations": dest_groups,
                        "bidirectional": True
                    }
                ]
            }
            resp = await client.post(
                f"{self.base_url}/policies",
                headers=self.headers,
                json=payload
            )
            if resp.status_code != 200:
                print(f"Netbird API Error (create_policy): {resp.text}")
                return None
            return resp.json().get('id')

    async def delete_policy(self, policy_id: str) -> bool:
        """Deletes a policy in Netbird."""
        async with httpx.AsyncClient() as client:
            resp = await client.delete(f"{self.base_url}/policies/{policy_id}", headers=self.headers)
            if resp.status_code != 200:
                print(f"Netbird API Error (delete_policy): {resp.text}")
                return False
            return True

    async def delete_group(self, group_id: str) -> bool:
        """Deletes a group in Netbird."""
        async with httpx.AsyncClient() as client:
            resp = await client.delete(f"{self.base_url}/groups/{group_id}", headers=self.headers)
            return resp.status_code == 200

    async def update_user_auto_groups(self, user_id: str, group_ids: list[str]) -> bool:
        """Updates user's auto_groups."""
        async with httpx.AsyncClient() as client:
            resp_get = await client.get(f"{self.base_url}/users/{user_id}", headers=self.headers)
            if resp_get.status_code != 200:
                print(f"Netbird API Error (get_user): {resp_get.text}")
                return False
            user_data = resp_get.json()
            
            payload = {
                "role": user_data.get("role", "user"),
                "auto_groups": group_ids,
                "is_service_user": user_data.get("is_service_user", False)
            }
            resp = await client.put(f"{self.base_url}/users/{user_id}", headers=self.headers, json=payload)
            if resp.status_code != 200:
                print(f"Netbird API Error (update_user_auto_groups): {resp.text}")
                return False
            return True

netbird = NetbirdClient()
